# Use postgres/example user/password credentials
version: '2.0'

services:

  db:
    image: mdillon/postgis
    restart: always
    ports:
      - 5342:5432
    environment:
      POSTGRES_PASSWORD: therm0s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
